# Site settings
title: Learn & Share
description: 
url: "https://www.spraphul.github.io"
author:
  name: "Praphul Singh"
  email: "praphulsingh1996@gmail.com"
  url: ""

plugins:
  - jekyll-toc

toc:
  min_level: 1       # Minimum heading level to include in the TOC (e.g., h1)
  max_level: 6       # Maximum heading level to include in the TOC (e.g., h6)
  no_toc_section_class: no_toc_section
  list_number: true  # Enable numbering in the TOC
  list_class: toc    # Class name for the TOC list

  
# Build settings
baseurl: /blog # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false

# Theme
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: dark 
